/* 
 * Bacalhau API
 *
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bacalhau-client.Api;
using bacalhau-client.Model;
using bacalhau-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace bacalhau-client.Test
{
    /// <summary>
    ///  Class for testing ModelPublishedResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelPublishedResultTests
    {
        // TODO uncomment below to declare an instance variable for ModelPublishedResult
        //private ModelPublishedResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelPublishedResult
            //instance = new ModelPublishedResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelPublishedResult
        /// </summary>
        [Test]
        public void ModelPublishedResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelPublishedResult
            //Assert.IsInstanceOfType<ModelPublishedResult> (instance, "variable 'instance' is a ModelPublishedResult");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'NodeID'
        /// </summary>
        [Test]
        public void NodeIDTest()
        {
            // TODO unit test for the property 'NodeID'
        }
        /// <summary>
        /// Test the property 'ShardIndex'
        /// </summary>
        [Test]
        public void ShardIndexTest()
        {
            // TODO unit test for the property 'ShardIndex'
        }

    }

}
