/* 
 * Bacalhau API
 *
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bacalhau-client.Api;
using bacalhau-client.Model;
using bacalhau-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace bacalhau-client.Test
{
    /// <summary>
    ///  Class for testing PublicapiListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PublicapiListResponseTests
    {
        // TODO uncomment below to declare an instance variable for PublicapiListResponse
        //private PublicapiListResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublicapiListResponse
            //instance = new PublicapiListResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicapiListResponse
        /// </summary>
        [Test]
        public void PublicapiListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PublicapiListResponse
            //Assert.IsInstanceOfType<PublicapiListResponse> (instance, "variable 'instance' is a PublicapiListResponse");
        }


        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Test]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }

    }

}
