/* 
 * Bacalhau API
 *
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bacalhau-client.Api;
using bacalhau-client.Model;
using bacalhau-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace bacalhau-client.Test
{
    /// <summary>
    ///  Class for testing PublicapiListRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PublicapiListRequestTests
    {
        // TODO uncomment below to declare an instance variable for PublicapiListRequest
        //private PublicapiListRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublicapiListRequest
            //instance = new PublicapiListRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicapiListRequest
        /// </summary>
        [Test]
        public void PublicapiListRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PublicapiListRequest
            //Assert.IsInstanceOfType<PublicapiListRequest> (instance, "variable 'instance' is a PublicapiListRequest");
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'MaxJobs'
        /// </summary>
        [Test]
        public void MaxJobsTest()
        {
            // TODO unit test for the property 'MaxJobs'
        }
        /// <summary>
        /// Test the property 'ReturnAll'
        /// </summary>
        [Test]
        public void ReturnAllTest()
        {
            // TODO unit test for the property 'ReturnAll'
        }
        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Test]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }
        /// <summary>
        /// Test the property 'SortReverse'
        /// </summary>
        [Test]
        public void SortReverseTest()
        {
            // TODO unit test for the property 'SortReverse'
        }

    }

}
