# Use the docker:dind image as the base image
FROM traefik:3.2

# Install curl and bash
RUN apk update && apk add --no-cache curl bash

# Install the ca-certificates package
RUN apk add --no-cache ca-certificates

# Copy a root ca into the image
COPY ./common_assets/certificates/generated_assets/bacalhau_test_root_ca.crt /usr/local/share/ca-certificates/bacalhau_test_root_ca.crt

# Update CA certificates
RUN update-ca-certificates

# Copy Tests Assets
RUN mkdir -p /bacalhau_integration_tests
COPY ./ /bacalhau_integration_tests
