# Use the docker:dind image as the base image
FROM alpine:latest

# Set the working directory
WORKDIR /app

# Install curl and bash
RUN apk update && apk add --no-cache curl bash

# Install the ca-certificates package
RUN apk add --no-cache ca-certificates

# Copy a root ca into the image
COPY ./common_assets/certificates/generated_assets/bacalhau_test_root_ca.crt /usr/local/share/ca-certificates/bacalhau_test_root_ca.crt

# Update CA certificates
RUN update-ca-certificates

# Copy Tests Assets
RUN mkdir -p /bacalhau_integration_tests
COPY ./ /bacalhau_integration_tests

# Download and execute the Bash script from the given URL
COPY ./common_assets/bacalhau_bin /usr/local/bin/bacalhau
RUN chmod +x /usr/local/bin/bacalhau

# Download the minio cli binary, make it executable, and move it to /usr/local/bin
RUN curl -o /tmp/mc https://dl.min.io/client/mc/release/linux-amd64/mc \
    && chmod +x /tmp/mc \
    && mv /tmp/mc /usr/local/bin/
