Node:
  Type:
    - requester
  ClientAPI:
    Host: 0.0.0.0
    Port: 1234
  BootstrapAddresses:
  Compute:
    JobSelection:
      Locality: anywhere
      AcceptNetworkedJobs: ${bacalhau_accept_networked_jobs}
  WebUI: true
  UpdateConfig:
    SkipChecks: true