# create the bacalhau user that will run the bacalhau process
packages:
  - vim

users:
  - name: bacalhau
    groups: docker
    system: true
    shell: /usr/sbin/nologin

write_files:
  # bacalhau config
  - path: /bacalhau_repo/config.yaml
    encoding: b64
    owner: bacalhau:bacalhau
    permissions: "0600"
    defer: true
    content: |
      ${bacalhau_config_file}

    # tls cert
  - path: /bacalhau_repo/bacalhau_cert.crt
    encoding: b64
    owner: bacalhau:bacalhau
    permissions: "0400"
    defer: true
    content: |
      ${tls_cert_file}

  # Runs at every boot to ensure disks are mounted. Ensures on instance restarts disks are mounted.
  - path: /var/lib/cloud/scripts/per-boot/mount-bacalhau-disks.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      is_mounted() {
        mountpoint -q "$1"
      }
      if ! is_mounted "/bacalhau_repo"; then
        mount /bacalhau_repo 2>/dev/null || true
      fi
      if ! is_mounted "/bacalhau_local_data"; then
        mount /bacalhau_local_data 2>/dev/null || true
      fi

  # bacalhau service file to run the bacalhau process
  - path: /etc/systemd/system/bacalhau.service
    encoding: b64
    owner: root:root
    permissions: "0600"
    content: |
      ${bacalhau_service_file}

  # bacalhau install-script to install a custom bacalhau version
  - path: /etc/install-bacalhau.sh
    encoding: b64
    owner: root:root
    permissions: "0600"
    content: |
      ${bacalhau_install_script_file}

  # otel config file
  - path: /etc/otel-collector.yaml
    encoding: b64
    owner: root:root
    permissions: "0600"
    content: |
      ${otel_config_file}

  # otel service file
  - path: /etc/systemd/system/otel.service
    encoding: b64
    owner: root:root
    permissions: "0600"
    content: |
      ${otel_service_file}


# setup and mount the bacalhau repo attached disk
disk_setup:
  /dev/disk/by-id/google-bacalhau-repo:
    table_type: 'gpt'
    layout: true
    overwrite: false

  /dev/disk/by-id/google-bacalhau-local:
    table_type: 'gpt'
    layout: true
    overwrite: false

fs_setup:
  - device: /dev/disk/by-id/google-bacalhau-repo
    filesystem: 'ext4'
    overwrite: false
  - device: /dev/disk/by-id/google-bacalhau-local
    filesystem: 'ext4'
    overwrite: false

mounts:
  - [ /dev/disk/by-id/google-bacalhau-repo, /bacalhau_repo, auto, "defaults,nofail", "0", "2" ]
  - [ /dev/disk/by-id/google-bacalhau-local, /bacalhau_local_data, auto, "defaults,nofail", "0", "2" ]


# change the owner of the bacalhau repo to the bacalhau user
runcmd:
  - chown -R bacalhau:bacalhau /bacalhau_repo
  - chown -R bacalhau:bacalhau /bacalhau_local_data
