/**
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param clientId 
 * @param id 
 * @param maxJobs 
 * @param returnAll 
 * @param sortBy 
 * @param sortReverse 
 */
data class PublicapilistRequest (

    val clientId: kotlin.String? = null,
    val id: kotlin.String? = null,
    val maxJobs: kotlin.Int? = null,
    val returnAll: kotlin.Boolean? = null,
    val sortBy: kotlin.String? = null,
    val sortReverse: kotlin.Boolean? = null
) {
}