/**
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param nodeId which node is running this shard
 * @param publishedResults 
 * @param runOutput 
 * @param shardIndex what shard is this we are running
 * @param state what is the state of the shard on this node
 * @param status an arbitrary status message
 * @param verificationProposal the proposed results for this shard this will be resolved by the verifier somehow
 * @param verificationResult 
 */
case class JobShardState (
  nodeId: Option[String] = None,
  publishedResults: Option[model.StorageSpec] = None,
  runOutput: Option[model.RunCommandResult] = None,
  shardIndex: Option[Integer] = None,
  state: Option[Integer] = None,
  status: Option[String] = None,
  verificationProposal: Option[List[Integer]] = None,
  verificationResult: Option[model.VerificationResult] = None
)

