x-common-env-variables: &common-env-variables
  NETWORK_AUTH_TOKEN: "i_am_very_secret_token"
  BACALHAU_API_PORT: "1234"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadminpass"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadminpass"
  BACALHAU_UPDATECONFIG_INTERVAL: "0"
  BACALHAU_DISABLEANALYTICS: true

networks:
  bacalhau-network:
    driver: bridge

services:
  bacalhau-minio-node:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - bacalhau-network
    environment: *common-env-variables
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 2s

  bacalhau-container-img-registry-node:
    image: {{ .RegistryImageName }}
    restart: always
    networks:
      - bacalhau-network
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/bacalhau-container-img-registry-node.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/bacalhau-container-img-registry-node.key"
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv localhost 5000" ]
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 2s

  bacalhau-orchestrator-node:
    image: {{ .OrchestratorImageName }}
    networks:
      - bacalhau-network
    environment: *common-env-variables
    depends_on:
      bacalhau-minio-node:
        condition: service_healthy
    privileged: true
    command:
      - /bin/bash
      - -c
      - |
        {{ .OrchestratorStartCommand }}
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv localhost 1234" ]
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 2s

  bacalhau-compute-node:
    image: {{ .ComputeImageName }}
    privileged: true
    networks:
      - bacalhau-network
    depends_on:
      bacalhau-orchestrator-node:
        condition: service_healthy
      bacalhau-container-img-registry-node:
        condition: service_healthy
    environment:
      <<: *common-env-variables
      ORCHESTRATOR_NODE_LINK: 'bacalhau-orchestrator-node'
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv localhost 1234" ]
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 2s

  bacalhau-jumpbox-node:
    image: {{ .JumpboxImageName }}
    privileged: true
    networks:
      - bacalhau-network
    depends_on:
      bacalhau-orchestrator-node:
        condition: service_healthy
      bacalhau-compute-node:
        condition: service_healthy
      bacalhau-container-img-registry-node:
        condition: service_healthy
    environment:
      <<: *common-env-variables
      BACALHAU_API_HOST: 'bacalhau-orchestrator-node'
      BACALHAU_COMPUTE_NODE_HOST: 'bacalhau-compute-node'
      BACALHAU_MINIO_NODE_HOST: 'bacalhau-minio-node'
