x-common-env-variables: &common-env-variables
  NETWORK_AUTH_TOKEN: "i_am_very_secret_token"
  BACALHAU_UPDATECONFIG_INTERVAL: "0"
  BACALHAU_DISABLEANALYTICS: true

networks:
  bacalhau-network:
    driver: bridge

services:
  bacalhau-orchestrator-node:
    image: {{ .OrchestratorImageName }}
    networks:
      - bacalhau-network
    environment: *common-env-variables
    privileged: true
    command:
      - /bin/bash
      - -c
      - |
        {{ .OrchestratorStartCommand }}
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv localhost 5555" ]
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 2s

  bacalhau-jumpbox-node:
    image: {{ .JumpboxImageName }}
    privileged: true
    command: tail -f /dev/null
    restart: unless-stopped
    networks:
      - bacalhau-network
    ## In the Environment variable we only specify a URL with port as host
    environment:
      <<: *common-env-variables
      BACALHAU_API_HOST: 'http://bacalhau-orchestrator-node:5555'
