# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      go build
      cd ..
      wget https://dist.ipfs.io/go-ipfs/v0.11.0/go-ipfs_v0.11.0_linux-amd64.tar.gz
      tar -xvzf go-ipfs_v0.11.0_linux-amd64.tar.gz
      sudo bash go-ipfs/install.sh

    command: echo 'start script'

vscode:
  extensions:
    - hashicorp.terraform