run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true
  concurrency: 4

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - ineffassign
    - unused
    - gosimple
    - staticcheck
    - typecheck
  disable-all: false
  fast: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - path: webui/webui\.go
      linters:
        - typecheck
  exclude:
    - 'shadow: declaration of "err" shadows declaration at'
  exclude-dirs:
    - ./.*
    - webui/.*
    - webui/build
    - webui/node_modules
    - vendor
    - ops
  exclude-files:
    - webui/webui.go
