- name: Deploy Golang App
  hosts: local
  tasks:

  - name: Ensure tools are installed
    become: yes
    apt:
      name:
        - git
        - golang
        - make
        - jq
        - docker
      state: present
    when: ansible_os_family == "Debian"

  - name: Set GOPATH
    become: yes
    become_user: frrist
    set_fact:
      GOPATH: "{{ ansible_env.HOME }}/go"

  - name: Clone the repository
    become: yes
    become_user: frrist
    git:
      repo: 'https://github.com/bacalhau-project/bacalhau.git'
      dest: "{{ ansible_env.HOME }}/bacalhau"
      version: "{{ git_branch }}"
      clone: yes
      update: yes

  - name: Build the Golang App
    become: yes
    become_user: frrist
    command:
      cmd: "make"
      chdir: "{{ ansible_env.HOME }}/bacalhau"

  - name: Setup the Repo
    become_user: frrist
    environment:
      BACALHAU_ENVIRONMENT: "local"
    command:
      cmd: "bacalhau id"
      chdir: "{{ ansible_env.HOME }}/bacalhau"

  - name: Setup Node Identity
    become_user: frrist
    copy:
      src: /home/frrist/src/github.com/bacalhau-project/bacalhau/ops/ansible/keys/libp2p_private_key
      dest: "{{ ansible_env.HOME }}/.bacalhau/libp2p_private_key"

  - name: Deploy bacalhau systemd service file from template
    become: yes
    template:
      src: "{{ ansible_env.HOME }}/bacalhau/ops/ansible/services/bacalhau.service.j2"
      dest: /etc/systemd/system/bacalhau.service
      mode: '0644'

  - name: Reload systemd to recognize bacalhau service
    become: yes
    command: systemctl daemon-reload

  - name: Enable and start bacalhau service
    become: yes
    systemd:
      name: bacalhau
      enabled: yes
      state: started
