// Code generated by "stringer -type=JobEventType --trimprefix=JobEvent"; DO NOT EDIT.

package executor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[jobEventUnknown-0]
	_ = x[JobEventCreated-1]
	_ = x[JobEventDealUpdated-2]
	_ = x[JobEventBid-3]
	_ = x[JobEventBidAccepted-4]
	_ = x[JobEventBidRejected-5]
	_ = x[JobEventBidCancelled-6]
	_ = x[JobEventPreparing-7]
	_ = x[JobEventRunning-8]
	_ = x[JobEventCompleted-9]
	_ = x[JobEventError-10]
	_ = x[JobEventResultsAccepted-11]
	_ = x[JobEventResultsRejected-12]
	_ = x[jobEventDone-13]
}

const _JobEventType_name = "jobEventUnknownCreatedDealUpdatedBidBidAcceptedBidRejectedBidCancelledPreparingRunningCompletedErrorResultsAcceptedResultsRejectedjobEventDone"

var _JobEventType_index = [...]uint8{0, 15, 22, 33, 36, 47, 58, 70, 79, 86, 95, 100, 115, 130, 142}

func (i JobEventType) String() string {
	if i < 0 || i >= JobEventType(len(_JobEventType_index)-1) {
		return "JobEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobEventType_name[_JobEventType_index[i]:_JobEventType_index[i+1]]
}
