// nolint:stylecheck // prefer caps for these
package util

const (
	OS_USER_R   = 0400
	OS_USER_W   = 0200
	OS_USER_X   = 0100
	OS_USER_RW  = OS_USER_R | OS_USER_W
	OS_USER_RWX = OS_USER_R | OS_USER_W | OS_USER_X

	OS_GROUP_R   = 0040
	OS_GROUP_W   = 0020
	OS_GROUP_X   = 0010
	OS_GROUP_RW  = OS_GROUP_R | OS_GROUP_W
	OS_GROUP_RWX = OS_GROUP_R | OS_GROUP_W | OS_GROUP_X

	OS_OTH_R   = 0004
	OS_OTH_W   = 0002
	OS_OTH_X   = 0001
	OS_OTH_RW  = OS_OTH_R | OS_OTH_W
	OS_OTH_RWX = OS_OTH_R | OS_OTH_W | OS_OTH_X

	OS_ALL_R   = OS_USER_R | OS_GROUP_R | OS_OTH_R
	OS_ALL_W   = OS_USER_W | OS_GROUP_W | OS_OTH_W
	OS_ALL_X   = OS_USER_X | OS_GROUP_X | OS_OTH_X
	OS_ALL_RW  = OS_USER_RW | OS_GROUP_RW | OS_OTH_RW
	OS_ALL_RWX = OS_USER_RWX | OS_GROUP_RWX | OS_OTH_RWX
)
