apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: tf-manifest
spec:
  runnerPodTemplate:
    spec:
      volumeMounts:
      - name: google-auth
        mountPath: "/etc/google-auth"
        readOnly: true
      volumes:
      - name: google-auth
        secret:
          secretName: google-auth
          optional: false
      env:
      - name: "GOOGLE_APPLICATION_CREDENTIALS"
        value: "/etc/google-auth/key.json"
      - name: "TF_WORKSPACE"
        value: "development"
  disableDriftDetection: true
  backendConfig:
    customConfiguration: |
      backend "gcs" {
        bucket = "bacalhau-global-storage"
        prefix = "terraform/state"
      }
  interval: 1m
  path: ./ops/terraform
  varsFrom:
  - name: env-values
    kind: ConfigMap
  vars:
  - name: ingress_cidrs
    value: ["0.0.0.0/0"]
  - name: ssh_access_cidrs
    value: ["0.0.0.0/0"]
  sourceRef:
    kind: GitRepository
    name: bacalhau