/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ModelResourceUsageData;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ComputenodeActiveJob
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T18:06:36.734351Z[Europe/London]")
public class ComputenodeActiveJob {
  @SerializedName("CapacityRequirements")
  private ModelResourceUsageData capacityRequirements = null;

  @SerializedName("ShardID")
  private String shardID = null;

  @SerializedName("State")
  private String state = null;

  public ComputenodeActiveJob capacityRequirements(ModelResourceUsageData capacityRequirements) {
    this.capacityRequirements = capacityRequirements;
    return this;
  }

   /**
   * Get capacityRequirements
   * @return capacityRequirements
  **/
  @Schema(description = "")
  public ModelResourceUsageData getCapacityRequirements() {
    return capacityRequirements;
  }

  public void setCapacityRequirements(ModelResourceUsageData capacityRequirements) {
    this.capacityRequirements = capacityRequirements;
  }

  public ComputenodeActiveJob shardID(String shardID) {
    this.shardID = shardID;
    return this;
  }

   /**
   * Get shardID
   * @return shardID
  **/
  @Schema(description = "")
  public String getShardID() {
    return shardID;
  }

  public void setShardID(String shardID) {
    this.shardID = shardID;
  }

  public ComputenodeActiveJob state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @Schema(description = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComputenodeActiveJob computenodeActiveJob = (ComputenodeActiveJob) o;
    return Objects.equals(this.capacityRequirements, computenodeActiveJob.capacityRequirements) &&
        Objects.equals(this.shardID, computenodeActiveJob.shardID) &&
        Objects.equals(this.state, computenodeActiveJob.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capacityRequirements, shardID, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComputenodeActiveJob {\n");
    
    sb.append("    capacityRequirements: ").append(toIndentedString(capacityRequirements)).append("\n");
    sb.append("    shardID: ").append(toIndentedString(shardID)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
