/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * ModelResourceUsageData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T18:06:36.734351Z[Europe/London]")
public class ModelResourceUsageData {
  @SerializedName("CPU")
  private BigDecimal CPU = null;

  @SerializedName("Disk")
  private Integer disk = null;

  @SerializedName("GPU")
  private Integer GPU = null;

  @SerializedName("Memory")
  private Integer memory = null;

  public ModelResourceUsageData CPU(BigDecimal CPU) {
    this.CPU = CPU;
    return this;
  }

   /**
   * cpu units
   * @return CPU
  **/
  @Schema(example = "9.600000000000001", description = "cpu units")
  public BigDecimal getCPU() {
    return CPU;
  }

  public void setCPU(BigDecimal CPU) {
    this.CPU = CPU;
  }

  public ModelResourceUsageData disk(Integer disk) {
    this.disk = disk;
    return this;
  }

   /**
   * bytes
   * @return disk
  **/
  @Schema(example = "212663867801", description = "bytes")
  public Integer getDisk() {
    return disk;
  }

  public void setDisk(Integer disk) {
    this.disk = disk;
  }

  public ModelResourceUsageData GPU(Integer GPU) {
    this.GPU = GPU;
    return this;
  }

   /**
   * Get GPU
   * @return GPU
  **/
  @Schema(example = "1", description = "")
  public Integer getGPU() {
    return GPU;
  }

  public void setGPU(Integer GPU) {
    this.GPU = GPU;
  }

  public ModelResourceUsageData memory(Integer memory) {
    this.memory = memory;
    return this;
  }

   /**
   * bytes
   * @return memory
  **/
  @Schema(example = "27487790694", description = "bytes")
  public Integer getMemory() {
    return memory;
  }

  public void setMemory(Integer memory) {
    this.memory = memory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelResourceUsageData modelResourceUsageData = (ModelResourceUsageData) o;
    return Objects.equals(this.CPU, modelResourceUsageData.CPU) &&
        Objects.equals(this.disk, modelResourceUsageData.disk) &&
        Objects.equals(this.GPU, modelResourceUsageData.GPU) &&
        Objects.equals(this.memory, modelResourceUsageData.memory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CPU, disk, GPU, memory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelResourceUsageData {\n");
    
    sb.append("    CPU: ").append(toIndentedString(CPU)).append("\n");
    sb.append("    disk: ").append(toIndentedString(disk)).append("\n");
    sb.append("    GPU: ").append(toIndentedString(GPU)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
