/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ModelJobShardState;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * ModelJobNodeState
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T18:06:36.734351Z[Europe/London]")
public class ModelJobNodeState {
  @SerializedName("Shards")
  private Map<String, ModelJobShardState> shards = null;

  public ModelJobNodeState shards(Map<String, ModelJobShardState> shards) {
    this.shards = shards;
    return this;
  }

  public ModelJobNodeState putShardsItem(String key, ModelJobShardState shardsItem) {
    if (this.shards == null) {
      this.shards = new HashMap<String, ModelJobShardState>();
    }
    this.shards.put(key, shardsItem);
    return this;
  }

   /**
   * Get shards
   * @return shards
  **/
  @Schema(description = "")
  public Map<String, ModelJobShardState> getShards() {
    return shards;
  }

  public void setShards(Map<String, ModelJobShardState> shards) {
    this.shards = shards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelJobNodeState modelJobNodeState = (ModelJobNodeState) o;
    return Objects.equals(this.shards, modelJobNodeState.shards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelJobNodeState {\n");
    
    sb.append("    shards: ").append(toIndentedString(shards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
