/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ModelBuildVersionInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PublicapiVersionResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T18:06:36.734351Z[Europe/London]")
public class PublicapiVersionResponse {
  @SerializedName("build_version_info")
  private ModelBuildVersionInfo buildVersionInfo = null;

  public PublicapiVersionResponse buildVersionInfo(ModelBuildVersionInfo buildVersionInfo) {
    this.buildVersionInfo = buildVersionInfo;
    return this;
  }

   /**
   * Get buildVersionInfo
   * @return buildVersionInfo
  **/
  @Schema(description = "")
  public ModelBuildVersionInfo getBuildVersionInfo() {
    return buildVersionInfo;
  }

  public void setBuildVersionInfo(ModelBuildVersionInfo buildVersionInfo) {
    this.buildVersionInfo = buildVersionInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicapiVersionResponse publicapiVersionResponse = (PublicapiVersionResponse) o;
    return Objects.equals(this.buildVersionInfo, publicapiVersionResponse.buildVersionInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buildVersionInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicapiVersionResponse {\n");
    
    sb.append("    buildVersionInfo: ").append(toIndentedString(buildVersionInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
