/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ModelJobLocalEvent;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PublicapiLocalEventsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-25T18:06:36.734351Z[Europe/London]")
public class PublicapiLocalEventsResponse {
  @SerializedName("localEvents")
  private List<ModelJobLocalEvent> localEvents = null;

  public PublicapiLocalEventsResponse localEvents(List<ModelJobLocalEvent> localEvents) {
    this.localEvents = localEvents;
    return this;
  }

  public PublicapiLocalEventsResponse addLocalEventsItem(ModelJobLocalEvent localEventsItem) {
    if (this.localEvents == null) {
      this.localEvents = new ArrayList<ModelJobLocalEvent>();
    }
    this.localEvents.add(localEventsItem);
    return this;
  }

   /**
   * Get localEvents
   * @return localEvents
  **/
  @Schema(description = "")
  public List<ModelJobLocalEvent> getLocalEvents() {
    return localEvents;
  }

  public void setLocalEvents(List<ModelJobLocalEvent> localEvents) {
    this.localEvents = localEvents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicapiLocalEventsResponse publicapiLocalEventsResponse = (PublicapiLocalEventsResponse) o;
    return Objects.equals(this.localEvents, publicapiLocalEventsResponse.localEvents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(localEvents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicapiLocalEventsResponse {\n");
    
    sb.append("    localEvents: ").append(toIndentedString(localEvents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
