set shell := ["sh", "-c"]
set allow-duplicate-recipes
set positional-arguments
set dotenv-load
set export

SWAGGER_JSON := "../../webui/public/swagger/swagger.json"
PYPI_VERSION := `python ../../scripts/get_current_version_for_builds.py --pep440`

all:
    error("Disabled due to out of date libraries. Will pick up when needed.")

test: all

# install-uv:
#     curl -LsSf https://astral.sh/uv/install.sh | sh

# setup: install-uv
# 	uv pip install -r dev-requirements.in

# test:
#     cd plugins && $(MAKE) test

# fmt:
# 	autoflake --remove-all-unused-imports --ignore-init-module-imports --ignore-pass-after-docstring --in-place -r plugins

# lint:
# 	mypy --explicit-package-bases plugins
# 	# allow-empty-bodies: Allow empty body in function.
# 	# disable-error-code="annotation-unchecked": Remove the warning "By default the bodies of untyped functions are not checked".
# 	# Mypy raises a warning because it cannot determine the type from the dataclass, despite we specified the type in the dataclass.
# 	mypy --allow-empty-bodies --disable-error-code="annotation-unchecked" tests/flytekit/unit/core
# 	# pre-commit run --all-files

# spellcheck:
# 	codespell -L "te,raison,fo" --skip="./docs/build,./.git" --ignore-words="./.cspell/custom-dictionary.txt"

# release:
# 	twine upload --verbose dist/* -u __token__ -p ${PYPI_TOKEN}
