name = "bacalhau"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders]
"exec:go"   = { enabled = true }
"docker:generic"   = { enabled = true }

[builders."docker:go"]
enabled                = true
build_base_image       = "golang:1.19-buster"

[builders."docker:generic".build_args]
build_image = "golang:alpine"
run_image = "scratch"

[runners]
"local:docker"  = { enabled = true }
"local:exec"    = { enabled = true }
"cluster:k8s"   = { enabled = true }

[[testcases]]
name = "catFileToStdout"
instances = { min = 1, max = 200, default = 1 }

[[testcases]]
name = "catFileToVolume"
instances = { min = 1, max = 200, default = 1 }
