package config_v2

import "github.com/spf13/viper"

func setDefaults(cfg BacalhauConfig) {
viper.SetDefault(NodeBootstrapAddresses, cfg.Node.BootstrapAddresses)
viper.SetDefault(NodeLoggingMode, cfg.Node.LoggingMode)
viper.SetDefault(NodeType, cfg.Node.Type)
viper.SetDefault(NodeEstuaryAPIKey, cfg.Node.EstuaryAPIKey)
viper.SetDefault(NodeAllowListedLocalPaths, cfg.Node.AllowListedLocalPaths)
viper.SetDefault(NodeDisabledFeaturesEngines, cfg.Node.DisabledFeatures.Engines)
viper.SetDefault(NodeDisabledFeaturesPublishers, cfg.Node.DisabledFeatures.Publishers)
viper.SetDefault(NodeDisabledFeaturesStorages, cfg.Node.DisabledFeatures.Storages)
viper.SetDefault(NodeLabels, cfg.Node.Labels)
viper.SetDefault(NodeAPIHost, cfg.Node.API.Host)
viper.SetDefault(NodeAPIPort, cfg.Node.API.Port)
viper.SetDefault(NodeLibp2pSwarmPort, cfg.Node.Libp2p.SwarmPort)
viper.SetDefault(NodeLibp2pPeerConnect, cfg.Node.Libp2p.PeerConnect)
viper.SetDefault(NodeIPFSConnect, cfg.Node.IPFS.Connect)
viper.SetDefault(NodeIPFSPrivateInternal, cfg.Node.IPFS.PrivateInternal)
viper.SetDefault(NodeIPFSSwarmAddresses, cfg.Node.IPFS.SwarmAddresses)
viper.SetDefault(NodeComputeClientIDBypass, cfg.Node.Compute.ClientIDBypass)
viper.SetDefault(NodeComputeIgnorePhysicalResourceLimits, cfg.Node.Compute.IgnorePhysicalResourceLimits)
viper.SetDefault(NodeComputeCapacityJobCPU, cfg.Node.Compute.Capacity.JobCPU)
viper.SetDefault(NodeComputeCapacityJobMemory, cfg.Node.Compute.Capacity.JobMemory)
viper.SetDefault(NodeComputeCapacityJobGPU, cfg.Node.Compute.Capacity.JobGPU)
viper.SetDefault(NodeComputeCapacityTotalCPU, cfg.Node.Compute.Capacity.TotalCPU)
viper.SetDefault(NodeComputeCapacityTotalMemory, cfg.Node.Compute.Capacity.TotalMemory)
viper.SetDefault(NodeComputeCapacityTotalGPU, cfg.Node.Compute.Capacity.TotalGPU)
viper.SetDefault(NodeComputeExecutionStoreType, cfg.Node.Compute.ExecutionStore.Type.String())
viper.SetDefault(NodeComputeExecutionStorePath, cfg.Node.Compute.ExecutionStore.Path)
viper.SetDefault(NodeRequesterExternalVerifierHook, cfg.Node.Requester.ExternalVerifierHook)
viper.SetDefault(NodeRequesterJobSelectionPolicyLocality, cfg.Node.Requester.JobSelectionPolicy.Locality.String())
viper.SetDefault(NodeRequesterJobSelectionPolicyRejectStatelessJobs, cfg.Node.Requester.JobSelectionPolicy.RejectStatelessJobs)
viper.SetDefault(NodeRequesterJobSelectionPolicyAcceptNetworkedJobs, cfg.Node.Requester.JobSelectionPolicy.AcceptNetworkedJobs)
viper.SetDefault(NodeRequesterJobSelectionPolicyProbeHTTP, cfg.Node.Requester.JobSelectionPolicy.ProbeHTTP)
viper.SetDefault(NodeRequesterJobSelectionPolicyProbeExec, cfg.Node.Requester.JobSelectionPolicy.ProbeExec)
viper.SetDefault(NodeRequesterJobStoreType, cfg.Node.Requester.JobStore.Type.String())
viper.SetDefault(NodeRequesterJobStorePath, cfg.Node.Requester.JobStore.Path)
viper.SetDefault(NodeUserUserKeyPath, cfg.User.UserKeyPath)
}
