/* tslint:disable */
/* eslint-disable */
/**
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ModelJobSpecDocker
 */
export interface ModelJobSpecDocker {
    /**
     * optionally override the default entrypoint
     * @type {Array<string>}
     * @memberof ModelJobSpecDocker
     */
    entrypoint?: Array<string>;
    /**
     * a map of env to run the container with
     * @type {Array<string>}
     * @memberof ModelJobSpecDocker
     */
    environmentVariables?: Array<string>;
    /**
     * this should be pullable by docker
     * @type {string}
     * @memberof ModelJobSpecDocker
     */
    image?: string;
    /**
     * working directory inside the container
     * @type {string}
     * @memberof ModelJobSpecDocker
     */
    workingDirectory?: string;
}
