steps:
  - label: ":asdf: Install ASDF"
    commands: |
      git config advice.detachedHead false
      git clone https://github.com/asdf-vm/asdf.git /root/.asdf --branch v0.14.0
      cd /root/.asdf
      git fetch origin
      git checkout master
      git pull --all
      git checkout tags/v0.14.0
      cd -
      echo '. "$HOME/.asdf/asdf.sh"' >> /root/.bashrc
      echo 'export PATH=$HOME/.asdf/bin:$HOME/.asdf/shims:"${PATH}"' >> /root/shared_state.sh
    key: asdf

  - label: ":earth: Install Earthly"
    commands: |
      source /root/shared_state.sh
      asdf plugin-add earthly
      asdf install
      earthly --version
    key: earthly
    depends_on: asdf

  - label: ":earth: Select Earthly satellite"
    commands: |
      source /root/shared_state.sh
      earthly account login --token $(buildkite-agent secret get EARTHLY_ACCOUNT_TOKEN)
      earthly sat select
    key: earthly-satellite
    depends_on: earthly

  - label: ":hammer: Build"
    commands: |
      source /root/shared_state.sh
      cd webui
      earthly --push +all
    key: build
    depends_on: earthly-satellite

  - label: ":test_tube: Test"
    commands: cd webui
      earthly --push +test
    key: test
    depends_on: build
