# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bacalhau-client.models.base_model_ import Model
from bacalhau-client import util


class ModelResourceUsageConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cpu: str=None, disk: str=None, gpu: str=None, memory: str=None):  # noqa: E501
        """ModelResourceUsageConfig - a model defined in Swagger

        :param cpu: The cpu of this ModelResourceUsageConfig.  # noqa: E501
        :type cpu: str
        :param disk: The disk of this ModelResourceUsageConfig.  # noqa: E501
        :type disk: str
        :param gpu: The gpu of this ModelResourceUsageConfig.  # noqa: E501
        :type gpu: str
        :param memory: The memory of this ModelResourceUsageConfig.  # noqa: E501
        :type memory: str
        """
        self.swagger_types = {
            'cpu': str,
            'disk': str,
            'gpu': str,
            'memory': str
        }

        self.attribute_map = {
            'cpu': 'CPU',
            'disk': 'Disk',
            'gpu': 'GPU',
            'memory': 'Memory'
        }
        self._cpu = cpu
        self._disk = disk
        self._gpu = gpu
        self._memory = memory

    @classmethod
    def from_dict(cls, dikt) -> 'ModelResourceUsageConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The model.ResourceUsageConfig of this ModelResourceUsageConfig.  # noqa: E501
        :rtype: ModelResourceUsageConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cpu(self) -> str:
        """Gets the cpu of this ModelResourceUsageConfig.

        https://github.com/BTBurke/k8sresource string  # noqa: E501

        :return: The cpu of this ModelResourceUsageConfig.
        :rtype: str
        """
        return self._cpu

    @cpu.setter
    def cpu(self, cpu: str):
        """Sets the cpu of this ModelResourceUsageConfig.

        https://github.com/BTBurke/k8sresource string  # noqa: E501

        :param cpu: The cpu of this ModelResourceUsageConfig.
        :type cpu: str
        """

        self._cpu = cpu

    @property
    def disk(self) -> str:
        """Gets the disk of this ModelResourceUsageConfig.


        :return: The disk of this ModelResourceUsageConfig.
        :rtype: str
        """
        return self._disk

    @disk.setter
    def disk(self, disk: str):
        """Sets the disk of this ModelResourceUsageConfig.


        :param disk: The disk of this ModelResourceUsageConfig.
        :type disk: str
        """

        self._disk = disk

    @property
    def gpu(self) -> str:
        """Gets the gpu of this ModelResourceUsageConfig.

        unsigned integer string  # noqa: E501

        :return: The gpu of this ModelResourceUsageConfig.
        :rtype: str
        """
        return self._gpu

    @gpu.setter
    def gpu(self, gpu: str):
        """Sets the gpu of this ModelResourceUsageConfig.

        unsigned integer string  # noqa: E501

        :param gpu: The gpu of this ModelResourceUsageConfig.
        :type gpu: str
        """

        self._gpu = gpu

    @property
    def memory(self) -> str:
        """Gets the memory of this ModelResourceUsageConfig.

        github.com/c2h5oh/datasize string  # noqa: E501

        :return: The memory of this ModelResourceUsageConfig.
        :rtype: str
        """
        return self._memory

    @memory.setter
    def memory(self, memory: str):
        """Sets the memory of this ModelResourceUsageConfig.

        github.com/c2h5oh/datasize string  # noqa: E501

        :param memory: The memory of this ModelResourceUsageConfig.
        :type memory: str
        """

        self._memory = memory
