# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bacalhau-client.models.base_model_ import Model
from bacalhau-client import util


class PublicapiListRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, client_id: str=None, id: str=None, max_jobs: int=None, return_all: bool=None, sort_by: str=None, sort_reverse: bool=None):  # noqa: E501
        """PublicapiListRequest - a model defined in Swagger

        :param client_id: The client_id of this PublicapiListRequest.  # noqa: E501
        :type client_id: str
        :param id: The id of this PublicapiListRequest.  # noqa: E501
        :type id: str
        :param max_jobs: The max_jobs of this PublicapiListRequest.  # noqa: E501
        :type max_jobs: int
        :param return_all: The return_all of this PublicapiListRequest.  # noqa: E501
        :type return_all: bool
        :param sort_by: The sort_by of this PublicapiListRequest.  # noqa: E501
        :type sort_by: str
        :param sort_reverse: The sort_reverse of this PublicapiListRequest.  # noqa: E501
        :type sort_reverse: bool
        """
        self.swagger_types = {
            'client_id': str,
            'id': str,
            'max_jobs': int,
            'return_all': bool,
            'sort_by': str,
            'sort_reverse': bool
        }

        self.attribute_map = {
            'client_id': 'client_id',
            'id': 'id',
            'max_jobs': 'max_jobs',
            'return_all': 'return_all',
            'sort_by': 'sort_by',
            'sort_reverse': 'sort_reverse'
        }
        self._client_id = client_id
        self._id = id
        self._max_jobs = max_jobs
        self._return_all = return_all
        self._sort_by = sort_by
        self._sort_reverse = sort_reverse

    @classmethod
    def from_dict(cls, dikt) -> 'PublicapiListRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The publicapi.listRequest of this PublicapiListRequest.  # noqa: E501
        :rtype: PublicapiListRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_id(self) -> str:
        """Gets the client_id of this PublicapiListRequest.


        :return: The client_id of this PublicapiListRequest.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: str):
        """Sets the client_id of this PublicapiListRequest.


        :param client_id: The client_id of this PublicapiListRequest.
        :type client_id: str
        """

        self._client_id = client_id

    @property
    def id(self) -> str:
        """Gets the id of this PublicapiListRequest.


        :return: The id of this PublicapiListRequest.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this PublicapiListRequest.


        :param id: The id of this PublicapiListRequest.
        :type id: str
        """

        self._id = id

    @property
    def max_jobs(self) -> int:
        """Gets the max_jobs of this PublicapiListRequest.


        :return: The max_jobs of this PublicapiListRequest.
        :rtype: int
        """
        return self._max_jobs

    @max_jobs.setter
    def max_jobs(self, max_jobs: int):
        """Sets the max_jobs of this PublicapiListRequest.


        :param max_jobs: The max_jobs of this PublicapiListRequest.
        :type max_jobs: int
        """

        self._max_jobs = max_jobs

    @property
    def return_all(self) -> bool:
        """Gets the return_all of this PublicapiListRequest.


        :return: The return_all of this PublicapiListRequest.
        :rtype: bool
        """
        return self._return_all

    @return_all.setter
    def return_all(self, return_all: bool):
        """Sets the return_all of this PublicapiListRequest.


        :param return_all: The return_all of this PublicapiListRequest.
        :type return_all: bool
        """

        self._return_all = return_all

    @property
    def sort_by(self) -> str:
        """Gets the sort_by of this PublicapiListRequest.


        :return: The sort_by of this PublicapiListRequest.
        :rtype: str
        """
        return self._sort_by

    @sort_by.setter
    def sort_by(self, sort_by: str):
        """Sets the sort_by of this PublicapiListRequest.


        :param sort_by: The sort_by of this PublicapiListRequest.
        :type sort_by: str
        """

        self._sort_by = sort_by

    @property
    def sort_reverse(self) -> bool:
        """Gets the sort_reverse of this PublicapiListRequest.


        :return: The sort_reverse of this PublicapiListRequest.
        :rtype: bool
        """
        return self._sort_reverse

    @sort_reverse.setter
    def sort_reverse(self, sort_reverse: bool):
        """Sets the sort_reverse of this PublicapiListRequest.


        :param sort_reverse: The sort_reverse of this PublicapiListRequest.
        :type sort_reverse: bool
        """

        self._sort_reverse = sort_reverse
