{
 "title": "Bacalhau Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Node Metadata",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bacalhau_bacalhau_node_info_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Receieved",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bacalhau_jobs_received_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs Accepted",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bacalhau_jobs_accepted_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs Completed",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bacalhau_jobs_completed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Docker Executions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bacalhau_docker_active_executions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active WASM Executions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bacalhau_wasm_active_executions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Job Duration over 5mins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(bacalhau_job_duration_milliseconds_sum[5m])\n/\nrate(bacalhau_job_duration_milliseconds_count[5m])",
     "legendFormat": "{{task_engine}}"
    }
   ]
  },
  {
   "title": "Averagef HTTP Requests Duration over 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(bacalhau_http_server_duration_milliseconds_sum[5m])\n/\nrate(bacalhau_http_server_duration_milliseconds_count[5m])",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Request Content Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bacalhau_http_server_request_content_length_bytes_total",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Response Content Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bacalhau_http_server_response_content_length_bytes_total",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Evaluatio Broker Cancelable",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bacalhau_eval_broker_cancelable",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evaluatio Broker Inflight",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 2, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bacalhau_eval_broker_inflight", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Evaluatio Broker Pending",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 4, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bacalhau_eval_broker_pending", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Evaluatio Broker Waiting",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bacalhau_eval_broker_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker Ack Faults",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bacalhau_worker_ack_faults_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Dequeue Faults",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 10, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bacalhau_worker_dequeue_faults_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Process Faults",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bacalhau_worker_process_faults_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}