NameProvider: "uuid"
API:
  Port: 1234
Orchestrator:
  Enabled: true
  Auth:
    Token: "i_am_very_secret_token"
  License:
    LocalPath: "/bacalhau_integration_tests/common_assets/licenses/test-license.json"
Labels:
  label1: label1Value
  label2: label2Value
