# coding: utf-8

"""
    Bacalhau API

    This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: team@bacalhau.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bacalhau_client
from bacalhau_client.models.model_job_node_state import ModelJobNodeState  # noqa: E501
from bacalhau_client.rest import ApiException


class TestModelJobNodeState(unittest.TestCase):
    """ModelJobNodeState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelJobNodeState(self):
        """Test ModelJobNodeState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bacalhau_client.models.model_job_node_state.ModelJobNodeState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
