/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ModelResourceUsageData} from './ModelResourceUsageData';

/**
 * The ComputenodeActiveJob model module.
 * @module model/ComputenodeActiveJob
 * @version 0.3.13
 */
export class ComputenodeActiveJob {
  /**
   * Constructs a new <code>ComputenodeActiveJob</code>.
   * @alias module:model/ComputenodeActiveJob
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ComputenodeActiveJob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComputenodeActiveJob} obj Optional instance to populate.
   * @return {module:model/ComputenodeActiveJob} The populated <code>ComputenodeActiveJob</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ComputenodeActiveJob();
      if (data.hasOwnProperty('CapacityRequirements'))
        obj.capacityRequirements = ModelResourceUsageData.constructFromObject(data['CapacityRequirements']);
      if (data.hasOwnProperty('ShardID'))
        obj.shardID = ApiClient.convertToType(data['ShardID'], 'String');
      if (data.hasOwnProperty('State'))
        obj.state = ApiClient.convertToType(data['State'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/ModelResourceUsageData} capacityRequirements
 */
ComputenodeActiveJob.prototype.capacityRequirements = undefined;

/**
 * @member {String} shardID
 */
ComputenodeActiveJob.prototype.shardID = undefined;

/**
 * @member {String} state
 */
ComputenodeActiveJob.prototype.state = undefined;

