/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ModelResourceUsageConfig model module.
 * @module model/ModelResourceUsageConfig
 * @version 0.3.13
 */
export class ModelResourceUsageConfig {
  /**
   * Constructs a new <code>ModelResourceUsageConfig</code>.
   * @alias module:model/ModelResourceUsageConfig
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModelResourceUsageConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelResourceUsageConfig} obj Optional instance to populate.
   * @return {module:model/ModelResourceUsageConfig} The populated <code>ModelResourceUsageConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelResourceUsageConfig();
      if (data.hasOwnProperty('CPU'))
        obj.CPU = ApiClient.convertToType(data['CPU'], 'String');
      if (data.hasOwnProperty('Disk'))
        obj.disk = ApiClient.convertToType(data['Disk'], 'String');
      if (data.hasOwnProperty('GPU'))
        obj.GPU = ApiClient.convertToType(data['GPU'], 'String');
      if (data.hasOwnProperty('Memory'))
        obj.memory = ApiClient.convertToType(data['Memory'], 'String');
    }
    return obj;
  }
}

/**
 * https://github.com/BTBurke/k8sresource string
 * @member {String} CPU
 */
ModelResourceUsageConfig.prototype.CPU = undefined;

/**
 * @member {String} disk
 */
ModelResourceUsageConfig.prototype.disk = undefined;

/**
 * unsigned integer string
 * @member {String} GPU
 */
ModelResourceUsageConfig.prototype.GPU = undefined;

/**
 * github.com/c2h5oh/datasize string
 * @member {String} memory
 */
ModelResourceUsageConfig.prototype.memory = undefined;

