/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ModelStorageSpec} from './ModelStorageSpec';

/**
 * The ModelJobSpecLanguage model module.
 * @module model/ModelJobSpecLanguage
 * @version 0.3.13
 */
export class ModelJobSpecLanguage {
  /**
   * Constructs a new <code>ModelJobSpecLanguage</code>.
   * @alias module:model/ModelJobSpecLanguage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModelJobSpecLanguage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelJobSpecLanguage} obj Optional instance to populate.
   * @return {module:model/ModelJobSpecLanguage} The populated <code>ModelJobSpecLanguage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelJobSpecLanguage();
      if (data.hasOwnProperty('Command'))
        obj.command = ApiClient.convertToType(data['Command'], 'String');
      if (data.hasOwnProperty('DeterministicExecution'))
        obj.deterministicExecution = ApiClient.convertToType(data['DeterministicExecution'], 'Boolean');
      if (data.hasOwnProperty('JobContext'))
        obj.jobContext = ModelStorageSpec.constructFromObject(data['JobContext']);
      if (data.hasOwnProperty('Language'))
        obj.language = ApiClient.convertToType(data['Language'], 'String');
      if (data.hasOwnProperty('LanguageVersion'))
        obj.languageVersion = ApiClient.convertToType(data['LanguageVersion'], 'String');
      if (data.hasOwnProperty('ProgramPath'))
        obj.programPath = ApiClient.convertToType(data['ProgramPath'], 'String');
      if (data.hasOwnProperty('RequirementsPath'))
        obj.requirementsPath = ApiClient.convertToType(data['RequirementsPath'], 'String');
    }
    return obj;
  }
}

/**
 * optional program specified on commandline, like python -c \"print(1+1)\"
 * @member {String} command
 */
ModelJobSpecLanguage.prototype.command = undefined;

/**
 * must this job be run in a deterministic context?
 * @member {Boolean} deterministicExecution
 */
ModelJobSpecLanguage.prototype.deterministicExecution = undefined;

/**
 * @member {module:model/ModelStorageSpec} jobContext
 */
ModelJobSpecLanguage.prototype.jobContext = undefined;

/**
 * e.g. python
 * @member {String} language
 */
ModelJobSpecLanguage.prototype.language = undefined;

/**
 * e.g. 3.8
 * @member {String} languageVersion
 */
ModelJobSpecLanguage.prototype.languageVersion = undefined;

/**
 * optional program path relative to the context dir. one of Command or ProgramPath must be specified
 * @member {String} programPath
 */
ModelJobSpecLanguage.prototype.programPath = undefined;

/**
 * optional requirements.txt (or equivalent) path relative to the context dir
 * @member {String} requirementsPath
 */
ModelJobSpecLanguage.prototype.requirementsPath = undefined;

