/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ModelJobSpecDocker model module.
 * @module model/ModelJobSpecDocker
 * @version 0.3.13
 */
export class ModelJobSpecDocker {
  /**
   * Constructs a new <code>ModelJobSpecDocker</code>.
   * @alias module:model/ModelJobSpecDocker
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModelJobSpecDocker</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelJobSpecDocker} obj Optional instance to populate.
   * @return {module:model/ModelJobSpecDocker} The populated <code>ModelJobSpecDocker</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelJobSpecDocker();
      if (data.hasOwnProperty('Entrypoint'))
        obj.entrypoint = ApiClient.convertToType(data['Entrypoint'], ['String']);
      if (data.hasOwnProperty('EnvironmentVariables'))
        obj.environmentVariables = ApiClient.convertToType(data['EnvironmentVariables'], ['String']);
      if (data.hasOwnProperty('Image'))
        obj.image = ApiClient.convertToType(data['Image'], 'String');
      if (data.hasOwnProperty('WorkingDirectory'))
        obj.workingDirectory = ApiClient.convertToType(data['WorkingDirectory'], 'String');
    }
    return obj;
  }
}

/**
 * optionally override the default entrypoint
 * @member {Array.<String>} entrypoint
 */
ModelJobSpecDocker.prototype.entrypoint = undefined;

/**
 * a map of env to run the container with
 * @member {Array.<String>} environmentVariables
 */
ModelJobSpecDocker.prototype.environmentVariables = undefined;

/**
 * this should be pullable by docker
 * @member {String} image
 */
ModelJobSpecDocker.prototype.image = undefined;

/**
 * working directory inside the container
 * @member {String} workingDirectory
 */
ModelJobSpecDocker.prototype.workingDirectory = undefined;

