/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ModelPublishedResult} from './ModelPublishedResult';

/**
 * The PublicapiResultsResponse model module.
 * @module model/PublicapiResultsResponse
 * @version 0.3.13
 */
export class PublicapiResultsResponse {
  /**
   * Constructs a new <code>PublicapiResultsResponse</code>.
   * @alias module:model/PublicapiResultsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PublicapiResultsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublicapiResultsResponse} obj Optional instance to populate.
   * @return {module:model/PublicapiResultsResponse} The populated <code>PublicapiResultsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PublicapiResultsResponse();
      if (data.hasOwnProperty('results'))
        obj.results = ApiClient.convertToType(data['results'], [ModelPublishedResult]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ModelPublishedResult>} results
 */
PublicapiResultsResponse.prototype.results = undefined;

