/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ModelJob} from './ModelJob';

/**
 * The PublicapiListResponse model module.
 * @module model/PublicapiListResponse
 * @version 0.3.13
 */
export class PublicapiListResponse {
  /**
   * Constructs a new <code>PublicapiListResponse</code>.
   * @alias module:model/PublicapiListResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PublicapiListResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublicapiListResponse} obj Optional instance to populate.
   * @return {module:model/PublicapiListResponse} The populated <code>PublicapiListResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PublicapiListResponse();
      if (data.hasOwnProperty('jobs'))
        obj.jobs = ApiClient.convertToType(data['jobs'], [ModelJob]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ModelJob>} jobs
 */
PublicapiListResponse.prototype.jobs = undefined;

