/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PublicapiEventsRequest model module.
 * @module model/PublicapiEventsRequest
 * @version 0.3.13
 */
export class PublicapiEventsRequest {
  /**
   * Constructs a new <code>PublicapiEventsRequest</code>.
   * @alias module:model/PublicapiEventsRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PublicapiEventsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublicapiEventsRequest} obj Optional instance to populate.
   * @return {module:model/PublicapiEventsRequest} The populated <code>PublicapiEventsRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PublicapiEventsRequest();
      if (data.hasOwnProperty('client_id'))
        obj.clientId = ApiClient.convertToType(data['client_id'], 'String');
      if (data.hasOwnProperty('job_id'))
        obj.jobId = ApiClient.convertToType(data['job_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} clientId
 */
PublicapiEventsRequest.prototype.clientId = undefined;

/**
 * @member {String} jobId
 */
PublicapiEventsRequest.prototype.jobId = undefined;

