/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ComputenodeActiveJob} from './ComputenodeActiveJob';
import {ModelResourceUsageData} from './ModelResourceUsageData';
import {RequesternodeActiveJob} from './RequesternodeActiveJob';

/**
 * The PublicapiDebugResponse model module.
 * @module model/PublicapiDebugResponse
 * @version 0.3.13
 */
export class PublicapiDebugResponse {
  /**
   * Constructs a new <code>PublicapiDebugResponse</code>.
   * @alias module:model/PublicapiDebugResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PublicapiDebugResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublicapiDebugResponse} obj Optional instance to populate.
   * @return {module:model/PublicapiDebugResponse} The populated <code>PublicapiDebugResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PublicapiDebugResponse();
      if (data.hasOwnProperty('AvailableComputeCapacity'))
        obj.availableComputeCapacity = ModelResourceUsageData.constructFromObject(data['AvailableComputeCapacity']);
      if (data.hasOwnProperty('ComputeJobs'))
        obj.computeJobs = ApiClient.convertToType(data['ComputeJobs'], [ComputenodeActiveJob]);
      if (data.hasOwnProperty('RequesterJobs'))
        obj.requesterJobs = ApiClient.convertToType(data['RequesterJobs'], [RequesternodeActiveJob]);
    }
    return obj;
  }
}

/**
 * @member {module:model/ModelResourceUsageData} availableComputeCapacity
 */
PublicapiDebugResponse.prototype.availableComputeCapacity = undefined;

/**
 * @member {Array.<module:model/ComputenodeActiveJob>} computeJobs
 */
PublicapiDebugResponse.prototype.computeJobs = undefined;

/**
 * @member {Array.<module:model/RequesternodeActiveJob>} requesterJobs
 */
PublicapiDebugResponse.prototype.requesterJobs = undefined;

