/*
 * Bacalhau API
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TypesMountStatus model module.
 * @module model/TypesMountStatus
 * @version 0.3.13
 */
export class TypesMountStatus {
  /**
   * Constructs a new <code>TypesMountStatus</code>.
   * @alias module:model/TypesMountStatus
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TypesMountStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TypesMountStatus} obj Optional instance to populate.
   * @return {module:model/TypesMountStatus} The populated <code>TypesMountStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TypesMountStatus();
      if (data.hasOwnProperty('All'))
        obj.all = ApiClient.convertToType(data['All'], 'Number');
      if (data.hasOwnProperty('Free'))
        obj.free = ApiClient.convertToType(data['Free'], 'Number');
      if (data.hasOwnProperty('Used'))
        obj.used = ApiClient.convertToType(data['Used'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} all
 */
TypesMountStatus.prototype.all = undefined;

/**
 * @member {Number} free
 */
TypesMountStatus.prototype.free = undefined;

/**
 * @member {Number} used
 */
TypesMountStatus.prototype.used = undefined;

