- name: Deploy Bacalhau systemd service file from template
  become: yes
  template:
    src: "/Users/frrist/Workspace/src/github.com/bacalhau-project/bacalhau/ops/ansible/services/bacalhau.service.j2"
    dest: /etc/systemd/system/bacalhau.service
    mode: '0644'

- name: Reload systemd to recognize bacalhau service
  become: yes
  command: systemctl daemon-reload

- name: Enable and start bacalhau service
  become: yes
  systemd:
    name: bacalhau
    enabled: yes
    state: started

