<?php
/**
 * ModelJobTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bacalhau API
 *
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModelJobTest Class Doc Comment
 *
 * @category    Class
 * @description ModelJob
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelJobTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelJob"
     */
    public function testModelJob()
    {
    }

    /**
     * Test attribute "api_version"
     */
    public function testPropertyApiVersion()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "deal"
     */
    public function testPropertyDeal()
    {
    }

    /**
     * Test attribute "execution_plan"
     */
    public function testPropertyExecutionPlan()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "job_events"
     */
    public function testPropertyJobEvents()
    {
    }

    /**
     * Test attribute "job_state"
     */
    public function testPropertyJobState()
    {
    }

    /**
     * Test attribute "local_job_events"
     */
    public function testPropertyLocalJobEvents()
    {
    }

    /**
     * Test attribute "requester_node_id"
     */
    public function testPropertyRequesterNodeId()
    {
    }

    /**
     * Test attribute "requester_public_key"
     */
    public function testPropertyRequesterPublicKey()
    {
    }

    /**
     * Test attribute "spec"
     */
    public function testPropertySpec()
    {
    }
}
