<?php
/**
 * ModelJobShardStateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bacalhau API
 *
 * This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: team@bacalhau.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ModelJobShardStateTest Class Doc Comment
 *
 * @category    Class
 * @description ModelJobShardState
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelJobShardStateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ModelJobShardState"
     */
    public function testModelJobShardState()
    {
    }

    /**
     * Test attribute "node_id"
     */
    public function testPropertyNodeId()
    {
    }

    /**
     * Test attribute "published_results"
     */
    public function testPropertyPublishedResults()
    {
    }

    /**
     * Test attribute "run_output"
     */
    public function testPropertyRunOutput()
    {
    }

    /**
     * Test attribute "shard_index"
     */
    public function testPropertyShardIndex()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "verification_proposal"
     */
    public function testPropertyVerificationProposal()
    {
    }

    /**
     * Test attribute "verification_result"
     */
    public function testPropertyVerificationResult()
    {
    }
}
