apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bacalhau-development

resources:
- ../../base

secretGenerator:
- name: override-vars
  files:
  - terraform.tfvars=env-vars.tfvars

# Last mile patches that change regularly(E.g., versions)
patchesStrategicMerge:
- flux-kustomization.yaml                 # Apply the google auth
- ./terraform.yaml
