Auth:
  AccessPolicyPath: "/bacalhau_repo/authz_policy.rego"
  Methods:
    shared_secret:
      type: ask
      policypath: "/bacalhau_repo/authn_policy.rego"
Node:
  Type:
    - requester
  ClientAPI:
    Host: 0.0.0.0
    Port: 1234
    # TLS:
      # TODO(simon) [fixme]: allow requester to generate its own cert
  Network:
    Type: nats
    Port: 4222
    AuthSecret: ${compute_api_token}
    Orchestrators:
      - nats://${compute_api_token}@127.0.0.1:4222
    Cluster:
      Name: global
      Port: 6222
  BootstrapAddresses:
  Compute:
    JobSelection:
      Locality: anywhere
      AcceptNetworkedJobs: ${bacalhau_accept_networked_jobs}
  UpdateConfig:
  WebUI:
    Enabled: true
    Port: 80
  SkipChecks: true