# Bacalhau API
#
# This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
#
# OpenAPI spec version: 1.0.0
# Contact: team@bacalhau.org
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ModelJobLocalEvent Class
#'
#' @field EventName 
#' @field JobID 
#' @field ShardIndex 
#' @field TargetNodeID 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelJobLocalEvent <- R6::R6Class(
  'ModelJobLocalEvent',
  public = list(
    `EventName` = NULL,
    `JobID` = NULL,
    `ShardIndex` = NULL,
    `TargetNodeID` = NULL,
    initialize = function(`EventName`, `JobID`, `ShardIndex`, `TargetNodeID`){
      if (!missing(`EventName`)) {
        stopifnot(is.numeric(`EventName`), length(`EventName`) == 1)
        self$`EventName` <- `EventName`
      }
      if (!missing(`JobID`)) {
        stopifnot(is.character(`JobID`), length(`JobID`) == 1)
        self$`JobID` <- `JobID`
      }
      if (!missing(`ShardIndex`)) {
        stopifnot(is.numeric(`ShardIndex`), length(`ShardIndex`) == 1)
        self$`ShardIndex` <- `ShardIndex`
      }
      if (!missing(`TargetNodeID`)) {
        stopifnot(is.character(`TargetNodeID`), length(`TargetNodeID`) == 1)
        self$`TargetNodeID` <- `TargetNodeID`
      }
    },
    toJSON = function() {
      ModelJobLocalEventObject <- list()
      if (!is.null(self$`EventName`)) {
        ModelJobLocalEventObject[['EventName']] <- self$`EventName`
      }
      if (!is.null(self$`JobID`)) {
        ModelJobLocalEventObject[['JobID']] <- self$`JobID`
      }
      if (!is.null(self$`ShardIndex`)) {
        ModelJobLocalEventObject[['ShardIndex']] <- self$`ShardIndex`
      }
      if (!is.null(self$`TargetNodeID`)) {
        ModelJobLocalEventObject[['TargetNodeID']] <- self$`TargetNodeID`
      }

      ModelJobLocalEventObject
    },
    fromJSON = function(ModelJobLocalEventJson) {
      ModelJobLocalEventObject <- jsonlite::fromJSON(ModelJobLocalEventJson)
      if (!is.null(ModelJobLocalEventObject$`EventName`)) {
        self$`EventName` <- ModelJobLocalEventObject$`EventName`
      }
      if (!is.null(ModelJobLocalEventObject$`JobID`)) {
        self$`JobID` <- ModelJobLocalEventObject$`JobID`
      }
      if (!is.null(ModelJobLocalEventObject$`ShardIndex`)) {
        self$`ShardIndex` <- ModelJobLocalEventObject$`ShardIndex`
      }
      if (!is.null(ModelJobLocalEventObject$`TargetNodeID`)) {
        self$`TargetNodeID` <- ModelJobLocalEventObject$`TargetNodeID`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "EventName": %d,
           "JobID": %s,
           "ShardIndex": %d,
           "TargetNodeID": %s
        }',
        self$`EventName`,
        self$`JobID`,
        self$`ShardIndex`,
        self$`TargetNodeID`
      )
    },
    fromJSONString = function(ModelJobLocalEventJson) {
      ModelJobLocalEventObject <- jsonlite::fromJSON(ModelJobLocalEventJson)
      self$`EventName` <- ModelJobLocalEventObject$`EventName`
      self$`JobID` <- ModelJobLocalEventObject$`JobID`
      self$`ShardIndex` <- ModelJobLocalEventObject$`ShardIndex`
      self$`TargetNodeID` <- ModelJobLocalEventObject$`TargetNodeID`
    }
  )
)
