# Bacalhau API
#
# This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
#
# OpenAPI spec version: 1.0.0
# Contact: team@bacalhau.org
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ModelJobNodeState Class
#'
#' @field Shards 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelJobNodeState <- R6::R6Class(
  'ModelJobNodeState',
  public = list(
    `Shards` = NULL,
    initialize = function(`Shards`){
      if (!missing(`Shards`)) {
        stopifnot(R6::is.R6(`Shards`))
        self$`Shards` <- `Shards`
      }
    },
    toJSON = function() {
      ModelJobNodeStateObject <- list()
      if (!is.null(self$`Shards`)) {
        ModelJobNodeStateObject[['Shards']] <- self$`Shards`$toJSON()
      }

      ModelJobNodeStateObject
    },
    fromJSON = function(ModelJobNodeStateJson) {
      ModelJobNodeStateObject <- jsonlite::fromJSON(ModelJobNodeStateJson)
      if (!is.null(ModelJobNodeStateObject$`Shards`)) {
        ShardsObject <- ModelJobShardState$new()
        ShardsObject$fromJSON(jsonlite::toJSON(ModelJobNodeStateObject$Shards, auto_unbox = TRUE))
        self$`Shards` <- ShardsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "Shards": %s
        }',
        self$`Shards`$toJSON()
      )
    },
    fromJSONString = function(ModelJobNodeStateJson) {
      ModelJobNodeStateObject <- jsonlite::fromJSON(ModelJobNodeStateJson)
      ModelJobShardStateObject <- ModelJobShardState$new()
      self$`Shards` <- ModelJobShardStateObject$fromJSON(jsonlite::toJSON(ModelJobNodeStateObject$Shards, auto_unbox = TRUE))
    }
  )
)
