# Bacalhau API
#
# This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
#
# OpenAPI spec version: 1.0.0
# Contact: team@bacalhau.org
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PublicapiLocalEventsResponse Class
#'
#' @field localEvents 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PublicapiLocalEventsResponse <- R6::R6Class(
  'PublicapiLocalEventsResponse',
  public = list(
    `localEvents` = NULL,
    initialize = function(`localEvents`){
      if (!missing(`localEvents`)) {
        stopifnot(is.list(`localEvents`), length(`localEvents`) != 0)
        lapply(`localEvents`, function(x) stopifnot(R6::is.R6(x)))
        self$`localEvents` <- `localEvents`
      }
    },
    toJSON = function() {
      PublicapiLocalEventsResponseObject <- list()
      if (!is.null(self$`localEvents`)) {
        PublicapiLocalEventsResponseObject[['localEvents']] <- lapply(self$`localEvents`, function(x) x$toJSON())
      }

      PublicapiLocalEventsResponseObject
    },
    fromJSON = function(PublicapiLocalEventsResponseJson) {
      PublicapiLocalEventsResponseObject <- jsonlite::fromJSON(PublicapiLocalEventsResponseJson)
      if (!is.null(PublicapiLocalEventsResponseObject$`localEvents`)) {
        self$`localEvents` <- lapply(PublicapiLocalEventsResponseObject$`localEvents`, function(x) {
          localEventsObject <- ModelJobLocalEvent$new()
          localEventsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          localEventsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "localEvents": [%s]
        }',
        lapply(self$`localEvents`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(PublicapiLocalEventsResponseJson) {
      PublicapiLocalEventsResponseObject <- jsonlite::fromJSON(PublicapiLocalEventsResponseJson)
      self$`localEvents` <- lapply(PublicapiLocalEventsResponseObject$`localEvents`, function(x) ModelJobLocalEvent$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
