# Bacalhau API
#
# This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
#
# OpenAPI spec version: 1.0.0
# Contact: team@bacalhau.org
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PublicapiStateRequest Class
#'
#' @field client_id 
#' @field job_id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PublicapiStateRequest <- R6::R6Class(
  'PublicapiStateRequest',
  public = list(
    `client_id` = NULL,
    `job_id` = NULL,
    initialize = function(`client_id`, `job_id`){
      if (!missing(`client_id`)) {
        stopifnot(is.character(`client_id`), length(`client_id`) == 1)
        self$`client_id` <- `client_id`
      }
      if (!missing(`job_id`)) {
        stopifnot(is.character(`job_id`), length(`job_id`) == 1)
        self$`job_id` <- `job_id`
      }
    },
    toJSON = function() {
      PublicapiStateRequestObject <- list()
      if (!is.null(self$`client_id`)) {
        PublicapiStateRequestObject[['client_id']] <- self$`client_id`
      }
      if (!is.null(self$`job_id`)) {
        PublicapiStateRequestObject[['job_id']] <- self$`job_id`
      }

      PublicapiStateRequestObject
    },
    fromJSON = function(PublicapiStateRequestJson) {
      PublicapiStateRequestObject <- jsonlite::fromJSON(PublicapiStateRequestJson)
      if (!is.null(PublicapiStateRequestObject$`client_id`)) {
        self$`client_id` <- PublicapiStateRequestObject$`client_id`
      }
      if (!is.null(PublicapiStateRequestObject$`job_id`)) {
        self$`job_id` <- PublicapiStateRequestObject$`job_id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "client_id": %s,
           "job_id": %s
        }',
        self$`client_id`,
        self$`job_id`
      )
    },
    fromJSONString = function(PublicapiStateRequestJson) {
      PublicapiStateRequestObject <- jsonlite::fromJSON(PublicapiStateRequestJson)
      self$`client_id` <- PublicapiStateRequestObject$`client_id`
      self$`job_id` <- PublicapiStateRequestObject$`job_id`
    }
  )
)
