# Bacalhau API
#
# This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
#
# OpenAPI spec version: 1.0.0
# Contact: team@bacalhau.org
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PublicapiDebugResponse Class
#'
#' @field AvailableComputeCapacity 
#' @field ComputeJobs 
#' @field RequesterJobs 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PublicapiDebugResponse <- R6::R6Class(
  'PublicapiDebugResponse',
  public = list(
    `AvailableComputeCapacity` = NULL,
    `ComputeJobs` = NULL,
    `RequesterJobs` = NULL,
    initialize = function(`AvailableComputeCapacity`, `ComputeJobs`, `RequesterJobs`){
      if (!missing(`AvailableComputeCapacity`)) {
        stopifnot(R6::is.R6(`AvailableComputeCapacity`))
        self$`AvailableComputeCapacity` <- `AvailableComputeCapacity`
      }
      if (!missing(`ComputeJobs`)) {
        stopifnot(is.list(`ComputeJobs`), length(`ComputeJobs`) != 0)
        lapply(`ComputeJobs`, function(x) stopifnot(R6::is.R6(x)))
        self$`ComputeJobs` <- `ComputeJobs`
      }
      if (!missing(`RequesterJobs`)) {
        stopifnot(is.list(`RequesterJobs`), length(`RequesterJobs`) != 0)
        lapply(`RequesterJobs`, function(x) stopifnot(R6::is.R6(x)))
        self$`RequesterJobs` <- `RequesterJobs`
      }
    },
    toJSON = function() {
      PublicapiDebugResponseObject <- list()
      if (!is.null(self$`AvailableComputeCapacity`)) {
        PublicapiDebugResponseObject[['AvailableComputeCapacity']] <- self$`AvailableComputeCapacity`$toJSON()
      }
      if (!is.null(self$`ComputeJobs`)) {
        PublicapiDebugResponseObject[['ComputeJobs']] <- lapply(self$`ComputeJobs`, function(x) x$toJSON())
      }
      if (!is.null(self$`RequesterJobs`)) {
        PublicapiDebugResponseObject[['RequesterJobs']] <- lapply(self$`RequesterJobs`, function(x) x$toJSON())
      }

      PublicapiDebugResponseObject
    },
    fromJSON = function(PublicapiDebugResponseJson) {
      PublicapiDebugResponseObject <- jsonlite::fromJSON(PublicapiDebugResponseJson)
      if (!is.null(PublicapiDebugResponseObject$`AvailableComputeCapacity`)) {
        AvailableComputeCapacityObject <- ModelResourceUsageData$new()
        AvailableComputeCapacityObject$fromJSON(jsonlite::toJSON(PublicapiDebugResponseObject$AvailableComputeCapacity, auto_unbox = TRUE))
        self$`AvailableComputeCapacity` <- AvailableComputeCapacityObject
      }
      if (!is.null(PublicapiDebugResponseObject$`ComputeJobs`)) {
        self$`ComputeJobs` <- lapply(PublicapiDebugResponseObject$`ComputeJobs`, function(x) {
          ComputeJobsObject <- ComputenodeActiveJob$new()
          ComputeJobsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          ComputeJobsObject
        })
      }
      if (!is.null(PublicapiDebugResponseObject$`RequesterJobs`)) {
        self$`RequesterJobs` <- lapply(PublicapiDebugResponseObject$`RequesterJobs`, function(x) {
          RequesterJobsObject <- RequesternodeActiveJob$new()
          RequesterJobsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          RequesterJobsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "AvailableComputeCapacity": %s,
           "ComputeJobs": [%s],
           "RequesterJobs": [%s]
        }',
        self$`AvailableComputeCapacity`$toJSON(),
        lapply(self$`ComputeJobs`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`RequesterJobs`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(PublicapiDebugResponseJson) {
      PublicapiDebugResponseObject <- jsonlite::fromJSON(PublicapiDebugResponseJson)
      ModelResourceUsageDataObject <- ModelResourceUsageData$new()
      self$`AvailableComputeCapacity` <- ModelResourceUsageDataObject$fromJSON(jsonlite::toJSON(PublicapiDebugResponseObject$AvailableComputeCapacity, auto_unbox = TRUE))
      self$`ComputeJobs` <- lapply(PublicapiDebugResponseObject$`ComputeJobs`, function(x) ComputenodeActiveJob$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`RequesterJobs` <- lapply(PublicapiDebugResponseObject$`RequesterJobs`, function(x) RequesternodeActiveJob$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
