# Bacalhau API
#
# This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.
#
# OpenAPI spec version: 1.0.0
# Contact: team@bacalhau.org
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PublicapiSubmitRequest Class
#'
#' @field client_public_key 
#' @field data 
#' @field signature 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PublicapiSubmitRequest <- R6::R6Class(
  'PublicapiSubmitRequest',
  public = list(
    `client_public_key` = NULL,
    `data` = NULL,
    `signature` = NULL,
    initialize = function(`client_public_key`, `data`, `signature`){
      if (!missing(`client_public_key`)) {
        stopifnot(is.character(`client_public_key`), length(`client_public_key`) == 1)
        self$`client_public_key` <- `client_public_key`
      }
      if (!missing(`data`)) {
        stopifnot(R6::is.R6(`data`))
        self$`data` <- `data`
      }
      if (!missing(`signature`)) {
        stopifnot(is.character(`signature`), length(`signature`) == 1)
        self$`signature` <- `signature`
      }
    },
    toJSON = function() {
      PublicapiSubmitRequestObject <- list()
      if (!is.null(self$`client_public_key`)) {
        PublicapiSubmitRequestObject[['client_public_key']] <- self$`client_public_key`
      }
      if (!is.null(self$`data`)) {
        PublicapiSubmitRequestObject[['data']] <- self$`data`$toJSON()
      }
      if (!is.null(self$`signature`)) {
        PublicapiSubmitRequestObject[['signature']] <- self$`signature`
      }

      PublicapiSubmitRequestObject
    },
    fromJSON = function(PublicapiSubmitRequestJson) {
      PublicapiSubmitRequestObject <- jsonlite::fromJSON(PublicapiSubmitRequestJson)
      if (!is.null(PublicapiSubmitRequestObject$`client_public_key`)) {
        self$`client_public_key` <- PublicapiSubmitRequestObject$`client_public_key`
      }
      if (!is.null(PublicapiSubmitRequestObject$`data`)) {
        dataObject <- ModelJobCreatePayload$new()
        dataObject$fromJSON(jsonlite::toJSON(PublicapiSubmitRequestObject$data, auto_unbox = TRUE))
        self$`data` <- dataObject
      }
      if (!is.null(PublicapiSubmitRequestObject$`signature`)) {
        self$`signature` <- PublicapiSubmitRequestObject$`signature`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "client_public_key": %s,
           "data": %s,
           "signature": %s
        }',
        self$`client_public_key`,
        self$`data`$toJSON(),
        self$`signature`
      )
    },
    fromJSONString = function(PublicapiSubmitRequestJson) {
      PublicapiSubmitRequestObject <- jsonlite::fromJSON(PublicapiSubmitRequestJson)
      self$`client_public_key` <- PublicapiSubmitRequestObject$`client_public_key`
      ModelJobCreatePayloadObject <- ModelJobCreatePayload$new()
      self$`data` <- ModelJobCreatePayloadObject$fromJSON(jsonlite::toJSON(PublicapiSubmitRequestObject$data, auto_unbox = TRUE))
      self$`signature` <- PublicapiSubmitRequestObject$`signature`
    }
  )
)
