// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package spec

import (
	"fmt"
	"io"
	"math"
	"sort"

	model "github.com/bacalhau-project/bacalhau/pkg/model"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *JobSpecWasm) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{165}); err != nil {
		return err
	}

	// t.EntryPoint (string) (string)
	if len("EntryPoint") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"EntryPoint\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("EntryPoint"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("EntryPoint")); err != nil {
		return err
	}

	if len(t.EntryPoint) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.EntryPoint was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.EntryPoint))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.EntryPoint)); err != nil {
		return err
	}

	// t.Parameters ([]string) (slice)
	if len("Parameters") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Parameters\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Parameters"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("Parameters")); err != nil {
		return err
	}

	if len(t.Parameters) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.Parameters was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Parameters))); err != nil {
		return err
	}
	for _, v := range t.Parameters {
		if len(v) > cbg.MaxLength {
			return xerrors.Errorf("Value in field v was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(v))); err != nil {
			return err
		}
		if _, err := io.WriteString(w, string(v)); err != nil {
			return err
		}
	}

	// t.EntryModule (model.StorageSpec) (struct)
	if len("EntryModule") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"EntryModule\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("EntryModule"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("EntryModule")); err != nil {
		return err
	}

	if err := t.EntryModule.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.ImportModules ([]model.StorageSpec) (slice)
	if len("ImportModules") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"ImportModules\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("ImportModules"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("ImportModules")); err != nil {
		return err
	}

	if len(t.ImportModules) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.ImportModules was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.ImportModules))); err != nil {
		return err
	}
	for _, v := range t.ImportModules {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}
	}

	// t.EnvironmentVariables ([]spec.KV) (slice)
	if len("EnvironmentVariables") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"EnvironmentVariables\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("EnvironmentVariables"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("EnvironmentVariables")); err != nil {
		return err
	}

	if len(t.EnvironmentVariables) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.EnvironmentVariables was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.EnvironmentVariables))); err != nil {
		return err
	}
	for _, v := range t.EnvironmentVariables {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}
	}
	return nil
}

func (t *JobSpecWasm) UnmarshalCBOR(r io.Reader) (err error) {
	*t = JobSpecWasm{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("JobSpecWasm: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t.EntryPoint (string) (string)
		case "EntryPoint":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.EntryPoint = string(sval)
			}
			// t.Parameters ([]string) (slice)
		case "Parameters":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > cbg.MaxLength {
				return fmt.Errorf("t.Parameters: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Parameters = make([]string, extra)
			}

			for i := 0; i < int(extra); i++ {

				{
					sval, err := cbg.ReadString(cr)
					if err != nil {
						return err
					}

					t.Parameters[i] = string(sval)
				}
			}

			// t.EntryModule (model.StorageSpec) (struct)
		case "EntryModule":

			{

				if err := t.EntryModule.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.EntryModule: %w", err)
				}

			}
			// t.ImportModules ([]model.StorageSpec) (slice)
		case "ImportModules":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > cbg.MaxLength {
				return fmt.Errorf("t.ImportModules: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.ImportModules = make([]model.StorageSpec, extra)
			}

			for i := 0; i < int(extra); i++ {

				var v model.StorageSpec
				if err := v.UnmarshalCBOR(cr); err != nil {
					return err
				}

				t.ImportModules[i] = v
			}

			// t.EnvironmentVariables ([]spec.KV) (slice)
		case "EnvironmentVariables":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > cbg.MaxLength {
				return fmt.Errorf("t.EnvironmentVariables: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.EnvironmentVariables = make([]KV, extra)
			}

			for i := 0; i < int(extra); i++ {

				var v KV
				if err := v.UnmarshalCBOR(cr); err != nil {
					return err
				}

				t.EnvironmentVariables[i] = v
			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}
func (t *KV) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Key (string) (string)
	if len("Key") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Key\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Key"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("Key")); err != nil {
		return err
	}

	if len(t.Key) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Key was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Key))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Key)); err != nil {
		return err
	}

	// t.Value (string) (string)
	if len("Value") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Value\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Value"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("Value")); err != nil {
		return err
	}

	if len(t.Value) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Value was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Value))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Value)); err != nil {
		return err
	}
	return nil
}

func (t *KV) UnmarshalCBOR(r io.Reader) (err error) {
	*t = KV{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("KV: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t.Key (string) (string)
		case "Key":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.Key = string(sval)
			}
			// t.Value (string) (string)
		case "Value":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.Value = string(sval)
			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}
