#
# This is a Flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1), manifest.toml(5) for more information.
#

version = 1

# List packages you wish to install in your environment inside
# # the `[install]` section.
# pkgs.mkShell {
#   hardeningDisable = [ "all" ];
#   packages = [
#     goEnv
#     gomod2nix
#     pkgs.golangci-lint
#     pkgs.go_1_21
#     pkgs.gotools
#     pkgs.go-junit-report
#     pkgs.go-task
#     pkgs.delve
#   ];
# }
[install]
direnv.pkg-path = "direnv"
golangci-lint.pkg-path = "golangci-lint"
gotools.pkg-path = "gotools"
go_1_21.pkg-path = "go_1_21"
go-junit-report.pkg-path = "go-junit-report"
python310.pkg-path = "python310"
just.pkg-path = "just"
gotestsum.pkg-path = "gotestsum"
bash.pkg-path = "bash"
gnumake.pkg-path = "gnumake"
gh.pkg-path = "gh"
buildkite-agent.pkg-path = "buildkite-agent"
pre-commit.pkg-path = "pre-commit"

# Set environment variables in the `[vars]` section. These variables may not
# reference one another, and are added to the environment without first
# expanding them. They are available for use in the `[profile]` and `[hook]`
# scripts.
[vars]
# message = "Howdy"

# The `hook.on-activate` script is run by the *bash* shell immediately upon
# activating an environment, and will not be invoked if Flox detects that the
# environment has previously been activated. Variables set by the script will
# be inherited by `[profile]` scripts defined below. Note that any stdout
# generated by the script will be redirected to stderr.
[hook]
on-activate = '''
  # Autogenerated by Flox

  echo "Beginning activation of Flox environment" >&2

  export PYTHON_DIR="$FLOX_ENV_CACHE/python3"
  if [ ! -d "$PYTHON_DIR" ]; then
    echo "Creating python virtual environment in $PYTHON_DIR"
    python3 -m venv "$PYTHON_DIR"
  fi

  source "$PYTHON_DIR"/bin/activate

  python -m pip install --upgrade pip

  pip install uv
  uv pip install -r requirements.txt

  # Install Go dependencies
  unset GOROOT
  go get .
  go mod vendor
  go mod tidy

  # End autogenerated by Flox
'''

# Scripts defined in the `[profile]` section are *sourced* by *your shell* and
# inherit environment variables set in the `[vars]` section and by `[hook]` scripts.
# The `profile.common` script is sourced by all shells and special care should be
# taken to ensure compatibility with all shells, after which exactly one of
# `profile.{bash,fish,tcsh,zsh}` is sourced by the corresponding shell.
[profile]
common = '''

echo "Activating python virtual environment" >&2
source "$PYTHON_DIR/bin/activate"

echo "Setting up Go environment" >&2
unset GOROOT
export GOENV="$FLOX_ENV_CACHE/goenv"
export GOOS="$(uname | tr '[:upper:]' '[:lower:]')"
export GOARCH="$(uname -m)"

# Need to unset for gcc to work properly
unset LD_LIBRARY_PATH
'''

# Additional options can be set in the `[options]` section. Refer to
# manifest.toml(5) for a list of available options.
[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
