#
# This is a Flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1), manifest.toml(5) for more information.
#

# List packages you wish to install in your environment inside
# # the `[install]` section.
# pkgs.mkShell {
#   hardeningDisable = [ "all" ];
#   packages = [
#     goEnv
#     gomod2nix
#     pkgs.golangci-lint
#     pkgs.go_1_21
#     pkgs.gotools
#     pkgs.go-junit-report
#     pkgs.go-task
#     pkgs.delve
#   ];
# }
[install]
direnv.pkg-path = "direnv"
golangci-lint.pkg-path = "golangci-lint"
nodejs.pkg-path = "nodejs"
pre-commit.pkg-path = "pre-commit"
pnpm.pkg-path = "nodePackages.pnpm"
gotools.pkg-path = "gotools"
poetry.pkg-path = "poetry"
go_1_21.pkg-path = "go_1_21"
go_1_21.version = "=1.21.10"
python310.pkg-path = "python310"
go-junit-report.pkg-path = "go-junit-report"

# Set environment variables in the `[vars]` section. These variables may not
# reference one another, and are added to the environment without first
# expanding them. They are available for use in the `[profile]` and `[hook]`
# scripts.
[vars]
# message = "Howdy"

# The `hook.on-activate` script is run by the *bash* shell immediately upon
# activating an environment, and will not be invoked if Flox detects that the
# environment has previously been activated. Variables set by the script will
# be inherited by `[profile]` scripts defined below. Note that any stdout
# generated by the script will be redirected to stderr.
[hook]
on-activate = '''
  # Autogenerated by Flox

  # Setup a Python virtual environment

  export PYTHON_DIR="$FLOX_ENV_CACHE/python"
  if [ ! -d "$PYTHON_DIR" ]; then
    echo "Creating python virtual environment in $PYTHON_DIR"
    python -m venv "$PYTHON_DIR"
  fi

  # Quietly activate venv and install packages in a subshell so
  # that the venv can be freshly activated in the profile section.
  (
    source "$PYTHON_DIR/bin/activate"
    # install the dependencies for this project based on pyproject.toml
    # <https://pip.pypa.io/en/stable/cli/pip_install/>
    pip install -e . --quiet
  )

  # Point GOENV to Flox environment cache
  unset GOROOT
  export GOENV="$FLOX_ENV_CACHE/goenv"

  # Install Go dependencies
  go get .

  # End autogenerated by Flox
'''

# Scripts defined in the `[profile]` section are *sourced* by *your shell* and
# inherit environment variables set in the `[vars]` section and by `[hook]` scripts.
# The `profile.common` script is sourced by all shells and special care should be
# taken to ensure compatibility with all shells, after which exactly one of
# `profile.{bash,fish,tcsh,zsh}` is sourced by the corresponding shell.
[profile]
bash = '''
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate"

  # End autogenerated by Flox
'''
zsh = '''
  # Autogenerated by Flox

  echo "Activating python virtual environment" >&2
  source "$PYTHON_DIR/bin/activate"

  # End autogenerated by Flox
'''

# Additional options can be set in the `[options]` section. Refer to
# manifest.toml(5) for a list of available options.
[options]
systems = ["aarch64-darwin"]
