//
// ModelJobSpecDocker.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelJobSpecDocker: Codable {

    /** optionally override the default entrypoint */
    public var entrypoint: [String]?
    /** a map of env to run the container with */
    public var environmentVariables: [String]?
    /** this should be pullable by docker */
    public var image: String?
    /** working directory inside the container */
    public var workingDirectory: String?

    public init(entrypoint: [String]? = nil, environmentVariables: [String]? = nil, image: String? = nil, workingDirectory: String? = nil) {
        self.entrypoint = entrypoint
        self.environmentVariables = environmentVariables
        self.image = image
        self.workingDirectory = workingDirectory
    }

    public enum CodingKeys: String, CodingKey { 
        case entrypoint = "Entrypoint"
        case environmentVariables = "EnvironmentVariables"
        case image = "Image"
        case workingDirectory = "WorkingDirectory"
    }

}
