VERSION 0.8
FROM node:20.8.1

WORKDIR /code

setup-yarn:
    RUN corepack enable && \
        yarn init -2 && \
        yarn set version 4.4.1
    COPY .yarnrc.yml ./

copy-deps-files:
    FROM +setup-yarn
    COPY package.json yarn.lock ./

install-deps:
    FROM +copy-deps-files
    RUN yarn install

copy-code:
    FROM +install-deps
    COPY --dir app components hooks lib ./
    COPY next.config.mjs postcss.config.mjs tailwind.config.ts tsconfig.json ./
    COPY .eslintrc.json .prettierrc ./

run-linter:
    FROM +copy-code
    RUN yarn lint

build-artifacts:
    FROM +run-linter
    RUN yarn build

# TODO: let all build from run-tests when we have tests
run-tests:
    FROM +build-artifacts
    COPY --dir test ./
    RUN yarn test

all:
    FROM +build-artifacts
    SAVE ARTIFACT /code/build AS LOCAL build
