set shell := ["bash", "-c"]
set allow-duplicate-recipes
set positional-arguments
set dotenv-load
set export

install-deps:
	#!/usr/bin/env bash
	#!/usr/bin/env bash
	unset LD_LIBRARY_PATH

	# Install corepack
	corepack enable
	corepack prepare yarn@stable
	yarn set version berry
	yarn config set nodeLinker node-modules
	yarn install

run-linter: install-deps
	yarn eslint

build-artifacts: run-linter
	yarn build:prod

run-tests: build-artifacts
	yarn test

all: run-tests
	echo "Build complete"
