set shell := ["bash", "-c"]
set allow-duplicate-recipes
set positional-arguments
set dotenv-load
set export

install-deps:
	#!/usr/bin/env bash
	export COREPACK_ENABLE_STRICT=0
	corepack --yes enable
	yarn set version berry
	yarn config set nodeLinker node-modules
	yarn install

run-linter: install-deps
	yarn eslint

build-artifacts: run-linter
	yarn build

run-tests: build-artifacts
	yarn test

all: run-tests
	echo "Build complete"
