// Code generated by "stringer -type=StorageType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownStorage-0]
	_ = x[BoltDB-1]
	_ = x[BadgerDB-2]
}

const _StorageType_name = "UnknownStorageBoltDBBadgerDB"

var _StorageType_index = [...]uint8{0, 14, 20, 28}

func (i StorageType) String() string {
	if i < 0 || i >= StorageType(len(_StorageType_index)-1) {
		return "StorageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageType_name[_StorageType_index[i]:_StorageType_index[i+1]]
}
