---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-secrets
spec:
  targetNamespace: bacalhau-development
  interval: 10m
  decryption:
    provider: sops
    secretRef:
      name: tenant-sops-gpg
  sourceRef:
    kind: GitRepository
    name: bacalhau
    namespace: flux-system
  path: "./ops/gitops/development/us-east-2/secrets"
  prune: true