# reopened with the relevant failures.
#
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bacalhau
spec:
  gitImplementation: go-git
  interval: 5m0s
  ref:
    branch: tf-controller-poc
  timeout: 60s
  url: https://github.com/steve-fraser/bacalhau