---
# Source: tf-controller/charts/tf-controller/templates/runner-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
---
# Source: tf-controller/charts/tf-controller/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tf-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-runner-role
subjects:
- kind: ServiceAccount
  name: tf-runner
  namespace: default