// Code generated by "stringer -type=JobEventType --trimprefix=JobEvent --output jobeventtype_string.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[jobEventUnknown-0]
	_ = x[JobEventInitialSubmission-1]
	_ = x[JobEventCreated-2]
	_ = x[JobEventDealUpdated-3]
	_ = x[JobEventBid-4]
	_ = x[JobEventBidAccepted-5]
	_ = x[JobEventBidRejected-6]
	_ = x[JobEventBidCancelled-7]
	_ = x[JobEventRunning-8]
	_ = x[JobEventComputeError-9]
	_ = x[JobEventResultsProposed-10]
	_ = x[JobEventResultsAccepted-11]
	_ = x[JobEventResultsRejected-12]
	_ = x[JobEventResultsPublished-13]
	_ = x[JobEventError-14]
	_ = x[JobEventCanceled-15]
	_ = x[JobEventInvalidRequest-16]
	_ = x[jobEventDone-17]
}

const _JobEventType_name = "jobEventUnknownInitialSubmissionCreatedDealUpdatedBidBidAcceptedBidRejectedBidCancelledRunningComputeErrorResultsProposedResultsAcceptedResultsRejectedResultsPublishedErrorCanceledInvalidRequestjobEventDone"

var _JobEventType_index = [...]uint8{0, 15, 32, 39, 50, 53, 64, 75, 87, 94, 106, 121, 136, 151, 167, 172, 180, 194, 206}

func (i JobEventType) String() string {
	if i < 0 || i >= JobEventType(len(_JobEventType_index)-1) {
		return "JobEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobEventType_name[_JobEventType_index[i]:_JobEventType_index[i+1]]
}
