// Code generated by "stringer -type=Publisher --trimprefix=Publisher"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[publisherUnknown-0]
	_ = x[PublisherNoop-1]
	_ = x[PublisherIpfs-2]
	_ = x[PublisherEstuary-3]
	_ = x[PublisherS3-4]
	_ = x[publisherDone-5]
}

const _Publisher_name = "publisherUnknownNoopIpfsEstuaryS3publisherDone"

var _Publisher_index = [...]uint8{0, 16, 20, 24, 31, 33, 46}

func (i Publisher) String() string {
	if i < 0 || i >= Publisher(len(_Publisher_index)-1) {
		return "Publisher(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Publisher_name[_Publisher_index[i]:_Publisher_index[i+1]]
}
