name: TestContainers Suite

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system for compiled binary (linux, darwin, windows)'
        required: true
        type: string
      arch:
        description: 'Architecture for compiled binary (amd64, arm64, etc.)'
        required: true
        type: string
      artifact_name:
        description: 'Name of the artifact containing the binary'
        required: false
        type: string
        default: ''
      go_version_file:
        description: 'Path to the file containing Go version'
        required: false
        default: 'go.work'
        type: string
      test_timeout:
        description: 'Timeout for tests in minutes'
        required: false
        default: 30
        type: number
      test_args:
        description: 'Additional arguments to pass to go test'
        required: false
        default: ''
        type: string
      junit_report:
        description: 'Whether to generate JUnit XML report'
        required: false
        default: true
        type: boolean

jobs:
  container-tests:
    name: Container Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.test_timeout }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate artifact name
        id: artifact
        run: |
          if [ -n "${{ inputs.artifact_name }}" ]; then
            echo "name=${{ inputs.artifact_name }}" >> $GITHUB_OUTPUT
          else
            echo "name=${{ inputs.os }}-${{ inputs.arch }}" >> $GITHUB_OUTPUT
          fi

      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: compiled-artifacts/

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go_version_file }}
          cache: true

      - name: Install gotestsum
        if: inputs.junit_report
        run: go install gotest.tools/gotestsum@latest

      - name: Prepare binary for tests
        shell: bash
        run: |
          echo "===> Extracting compiled artifact..."
          cd compiled-artifacts
          tar -xzf bacalhau_*.tar.gz
          cp ./bacalhau ../test_integration/common_assets/bacalhau_bin
          
          # Verify binary works
          ../test_integration/common_assets/bacalhau_bin version

      - name: Docker info
        run: |
          docker info
          docker version

      - name: Run container tests with gotestsum
        if: inputs.junit_report
        shell: bash
        run: |
          cd test_integration
          gotestsum --junitfile container-tests.xml \
            --format testname \
            --jsonfile container-tests.json \
            -- -v -count=1 ${{ inputs.test_args }} ./...

      - name: Run container tests directly
        if: inputs.junit_report == 'false'
        shell: bash
        run: |
          cd test_integration
          go test -v -count=1 ${{ inputs.test_args }} ./...

      - name: Upload test reports
        if: inputs.junit_report && (success() || failure())
        uses: actions/upload-artifact@v4
        with:
          name: container-tests-reports
          path: |
            test_integration/container-tests.xml
            test_integration/container-tests.json
          retention-days: 14