---
name: Codespell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v1
        with:
          exclude_file: integration/flyte/Makefile,testdata/bad_strings_full.txt,docs/.vale/styles,docs/package-lock.json,testdata,docs/docs/examples/model-training/Stable-Diffusion-Dreambooth/index.md,apps/job-info-consumer/consumer/go.sum
          ignore_words_file: .gitprecommit/codespell_ignore_words.txt
