name: Dependabot Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - "**.md"
  repository_dispatch:
    types: [ok-to-test]

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Trigger CircleCI Pipeline
        run: .circleci/trigger_pipeline.sh
        env:
          BRANCH: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.event.ref }}
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN }}

  auto-merge:
    runs-on: ubuntu-latest
    needs: trigger-circleci
    steps:
      - name: Auto merge PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const mergePayload = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            };
            github.pulls.merge(mergePayload);
