name: Main Branch Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: read
  checks: write

# Prevent multiple build workflows from running simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel in-progress runs for main branch builds

jobs:
  # Build all binaries for release
  build-binaries:
    name: Build Binaries
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  # Build summary job
  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-binaries]
    steps:
      - name: Build Summary
        run: |
          echo "## Main Branch Build" >> $GITHUB_STEP_SUMMARY
          echo "✅ All binaries have been successfully built." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Ready for future S3 deployment." >> $GITHUB_STEP_SUMMARY