name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: read
  packages: write  # Required for GHCR
  id-token: write  # Required for AWS authentication

# Prevent multiple build workflows from running simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build all binaries for release
  build-binaries:
    name: Binary
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  # Push binaries to S3
  publish-to-s3:
    name: Publish to S3
    needs: [build-binaries]
    uses: ./.github/workflows/_s3_publish.yml
    with:
      target_type: 'edge'
    secrets: inherit

  # Build and push Docker images
  publish-docker:
    name: Publish Docker
    needs: [ build-binaries ]
    uses: ./.github/workflows/_docker_publish.yml
    with:
      target_type: 'edge'
    secrets: inherit
