name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering
#  TODO: remove from pull_request
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  actions: read
  checks: write
  id-token: write  # Required for AWS authentication

# Prevent multiple build workflows from running simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel in-progress runs for main branch builds

jobs:  # Build all binaries for release
  build-binaries:
    name: Binary
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  # Push binaries to S3
  publish-to-s3:
    name: Publish to S3
    needs: [build-binaries]
    uses: ./.github/workflows/_s3_publish.yml
    with:
      target_type: 'main'
    secrets: inherit
