name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: read
  checks: write
  id-token: write  # Required for AWS authentication

# Prevent multiple nightly builds from running simultaneously
concurrency:
  group: ${{ github.workflow }}-nightly
  cancel-in-progress: true  # Cancel in-progress runs for nightly builds

jobs:
  # Build all binaries for release
  build-binaries:
    name: Binary
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  # Push binaries to S3
  publish-to-s3:
    name: Publish to S3
    needs: [build-binaries]
    uses: ./.github/workflows/_s3_publish.yml
    with:
      target_type: 'nightly'
    secrets: inherit

  # Build summary job
  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-binaries, publish-to-s3]
    steps:
      - name: Build Summary
        run: |
          echo "## Nightly Build" >> $GITHUB_STEP_SUMMARY
          echo "✅ All binaries have been successfully built and published to S3." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Binaries are available at s3://${{ vars.S3_BUCKET }}/nightly/" >> $GITHUB_STEP_SUMMARY