name: Static Analysis

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup common tools with caching
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache: true

      - name: Setup Dummy WebUi Build
        run: |
          mkdir -p webui/build && touch webui/build/index.html

      # Run all static analysis checks
      - name: Codespell
        run: |
          yarn global add cspell@latest
          make spellcheck-code

      - name: Validate Swagger
        uses: ./.github/actions/swagger-validation

      - name: Run pre-commit checks
        run: |
          python -m pip install pre-commit
          pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.5.1
        with:
          skip-cache: false
          version: v1.64.5
