name: Swagger Validation

on:
  pull_request:
    branches:
      - main

jobs:
  ensure-up-to-date:
    name: Ensure Up-to-date
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install swag (Swagger generator)
      - name: Install Swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
        shell: bash

      # Step 3: Generate the swagger.json
      - name: Generate Swagger file
        run: |
          make generate-swagger

      # Step 4: Compare the newly generated swagger.json with the committed swagger.json
      - name: Check for Swagger differences
        run: |
          git diff --exit-code pkg/swagger/swagger.json

      # Step 5: Fail the build if Swagger doesn't match
      - name: Fail if Swagger has differences
        if: failure()
        run: |
          echo "Swagger is outdated. Please regenerate it with 'make generate-swagger' and commit the changes."
          exit 1
