name: Swagger Validation

on:
  pull_request:
    branches:
      - main

jobs:
  ensure-up-to-date:
    name: Ensure Up-to-date
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate the swagger.json (customize this as per your repo setup)
      - name: Generate Swagger file
        run: |
          make generate-swagger
          echo "Swagger generated!"

      # Step 3: Compare the newly generated swagger.json with the committed swagger.json
      - name: Check for Swagger differences
        run: |
          git diff --exit-code pkg/swagger/swagger.json
        continue-on-error: true

      # Step 4: Fail the build if Swagger doesn't match
      - name: Fail if Swagger has differences
        if: failure()  # This will cause the workflow to fail if there was a diff in the previous step
        run: |
          echo "Swagger is outdated. Please regenerate it with 'make generate-swagger' and commit the changes."
          exit 1
