name: Trigger Deployment to Development on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Deployment
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.BACALHAU_VMI_DEPLOYMENT_SECRET }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/bacalhau-project/bacalhau-vmi/actions/workflows/deploy-commit.yaml/dispatches" \
          --data '{"ref": "main", "inputs": {"commit_reference": "${{ github.sha }}", "redeploy": "false"}}'