name: Ok to push to upstream

on:
  repository_dispatch:
    types: [ok-to-push-to-upstream]

permissions:
  contents: write
  pull-requests: write

jobs:
  trigger-push-to-upstream:
    runs-on: ubuntu-latest
    name: Push to upstream
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: hmarr/debug-action@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: "Trigger Push to Upstream"
        id: trigger-push-to-upstream-step
        run: |
          pip install PyGithub

          python ./.circleci/push-to-upstream-fork.py \
          --upstream_full_name ${{ github.event.client_payload.upstream_full_name }} \
          --upstream_branch ${{ github.event.client_payload.upstream_branch }} \
          --branch_spec ${{ github.event.client_payload.user }}/${{ github.event.client_payload.branch }} \
          --github_token ${{ secrets.GITHUB_TOKEN }}
