name: Build VMI on Bacalhau Release

on:
  release:
    types: [created]

jobs:
  handle-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger VMI Build
        env:
          REPO: ${{ github.repository }}
        run: |
          curl -L -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/$REPO/dispatches" \
          -d '{"event_type": "new-version-release", "client_payload": {"release_tag": "${{ github.ref_name }}"} }'
